# Generated by Django 4.1.1 on 2022-11-15 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
