# Generated by Django 4.1.1 on 2022-11-15 13:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0002_alter_subject_subjectcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Examiner.subject', to_field='subjectCode'),
            preserve_default=False,
        ),
    ]
