# Generated by Django 4.0.6 on 2022-09-26 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0002_city_country_position_province_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='toAddress',
        ),
        migrations.AddField(
            model_name='invitation',
            name='toAddress',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
