# Generated by Django 4.0.6 on 2022-09-30 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0003_remove_invitation_toaddress_invitation_toaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='ead',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ead',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.district'),
        ),
        migrations.AddField(
            model_name='ead',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.province'),
        ),
    ]
