# Generated by Django 4.1.1 on 2022-11-15 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0003_alter_paper_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=7),
            preserve_default=False,
        ),
    ]
