# Generated by Django 4.1.1 on 2022-11-15 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0004_paper_paper_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
