# Generated by Django 4.1.1 on 2022-10-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0005_districtcv_alter_ead_user_alter_examiner_district_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='districtcv',
            new_name='districtcsv',
        ),
    ]
