# Generated by Django 4.1.1 on 2022-11-15 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0005_paper_paper_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='ExaminerCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
