# Generated by Django 4.1.1 on 2022-11-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0006_alter_examiner_examinercode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='ExaminerCode',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
