# Generated by Django 4.1.1 on 2022-10-03 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0007_man'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Man',
        ),
    ]
