# Generated by Django 4.1.1 on 2022-11-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0007_alter_examiner_examinercode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examiner',
            name='session',
        ),
        migrations.AddField(
            model_name='examiner',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Examiner.session'),
        ),
    ]
