# Generated by Django 4.1.1 on 2022-10-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0008_delete_man'),
    ]

    operations = [
        migrations.DeleteModel(
            name='districtcsv',
        ),
    ]
