# Generated by Django 4.1.1 on 2022-11-16 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0008_remove_examiner_session_examiner_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='paper',
            field=models.ForeignKey(db_column='Paper_Number', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.paper'),
        ),
    ]
