# Generated by Django 4.1.1 on 2022-10-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0009_delete_districtcsv'),
    ]

    operations = [
        migrations.CreateModel(
            name='districtcsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
