# Generated by Django 4.1.1 on 2022-11-16 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0009_alter_examiner_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.subject', to_field='subjectCode'),
        ),
    ]
