# Generated by Django 4.1.1 on 2022-11-16 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0010_alter_examiner_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='subject',
            field=models.ForeignKey(blank=True, db_column='Subject_Code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.subject', to_field='subjectCode'),
        ),
    ]
