# Generated by Django 4.1.1 on 2022-11-17 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0011_alter_examiner_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center', models.CharField(blank=True, choices=[('LUSAKA', 'LUSAKA'), ('COPPERBELT', 'COPPERBELT'), ('MONZE', 'MONZE'), ('KAPIRI', 'KAPIRI'), ('LIVINGSTONE', 'LIVINGSTONE'), ('CHOMA', 'CHOMA'), ('MWANDI', 'MWANDI'), ('LUNTE', 'LUNTE'), ('MWENSE', 'MWENSE'), ('KASENENGWA', 'KASENENGWA'), ('CHISAMBA', 'CHISAMBA'), ('CHIBOMBO', 'CHIBOMBO')], max_length=50, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examiner.paper')),
            ],
        ),
    ]
