# Generated by Django 4.1.1 on 2022-10-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0012_alter_subject_subjectdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='availability',
            field=models.BooleanField(default=False),
        ),
    ]
