# Generated by Django 4.1.1 on 2022-10-05 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0014_bankbranch_subjectselector_bank_examiner_bankdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='branch',
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Examiner.bank'),
        ),
    ]
