# Generated by Django 4.1.1 on 2022-11-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0015_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'ADMIN'), (1, 'EAD'), (2, 'FAD'), (3, 'Examiner'), (4, 'Station-Admin')], default=1),
        ),
    ]
