# Generated by Django 4.1.1 on 2022-10-06 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0015_remove_bank_branch_bankbranch_bank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examiner',
            old_name='bankdetails',
            new_name='bank',
        ),
        migrations.AddField(
            model_name='examiner',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.bankbranch'),
        ),
    ]
