# Generated by Django 4.1.1 on 2022-11-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0017_alter_eczstaff_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ead',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='ead',
            name='NRC',
        ),
        migrations.RemoveField(
            model_name='ead',
            name='cell_Number',
        ),
        migrations.RemoveField(
            model_name='ead',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='ead',
            name='middle_name',
        ),
    ]
