# Generated by Django 4.1.1 on 2022-10-06 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0018_alter_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
