# Generated by Django 4.1.1 on 2022-11-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0018_remove_ead_address_remove_ead_nrc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ead',
            old_name='UserName',
            new_name='username',
        ),
    ]
