# Generated by Django 4.1.1 on 2022-11-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0019_rename_username_ead_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='NRC',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='cell_Number',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
