# Generated by Django 4.1.1 on 2022-10-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0019_staff_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'EAD'), (2, 'Staff'), (3, 'Examiner')], default=1),
        ),
    ]
