# Generated by Django 4.1.1 on 2022-10-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0020_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='examiner',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
