# Generated by Django 4.1.1 on 2022-11-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0020_remove_staff_address_remove_staff_nrc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='UserName',
            new_name='username',
        ),
    ]
