# Generated by Django 4.1.1 on 2022-11-22 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0021_rename_username_staff_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eczstaff',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.paper'),
        ),
    ]
