# Generated by Django 4.1.1 on 2022-10-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0021_examiner_first_name_examiner_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examiner',
            old_name='name',
            new_name='middle_name',
        ),
    ]
