# Generated by Django 4.1.1 on 2022-10-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0022_rename_name_examiner_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
