# Generated by Django 4.1.1 on 2022-11-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0023_alter_ead_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='mail_count',
            field=models.IntegerField(default=0),
        ),
    ]
