# Generated by Django 4.1.1 on 2022-10-17 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0024_alter_position_name_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
