# Generated by Django 4.1.1 on 2022-11-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0024_examiner_mail_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eczstaff',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='eczstaff',
            name='subject',
        ),
    ]
