# Generated by Django 4.1.1 on 2022-12-07 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0026_eczstaff_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='NRC',
            field=models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid NRC Number', regex='([0-9]{6})\\/([0-9]{2})\\/([0-9]{1})')]),
        ),
    ]
