# Generated by Django 4.1.1 on 2022-10-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0026_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ead',
            old_name='LastName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='ead',
            old_name='firstName',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='ead',
            name='AccountDetails',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='ead',
            name='NRC',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='ead',
            name='TPIN',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ead',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.bank'),
        ),
        migrations.AddField(
            model_name='ead',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.bankbranch'),
        ),
        migrations.AddField(
            model_name='ead',
            name='cell_Number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='ead',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ead',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
