# Generated by Django 4.1.1 on 2022-10-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0027_rename_lastname_ead_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ead',
            old_name='address',
            new_name='Address',
        ),
    ]
