# Generated by Django 4.1.1 on 2022-12-07 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0027_alter_examiner_nrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='TPIN',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid T-Pin Number [0~9 10 digits]', regex='([0-9]{10})')]),
        ),
    ]
