# Generated by Django 4.1.1 on 2022-10-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0028_rename_address_ead_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
