# Generated by Django 4.1.1 on 2022-10-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0030_remove_staff_username_remove_staff_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ead',
            name='NRC',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='ead',
            name='cell_Number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='NRC',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='cell_Number',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='NRC',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='cell_Number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
