# Generated by Django 4.1.1 on 2022-10-25 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0031_alter_ead_nrc_alter_ead_cell_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='fromAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Examiner.ead'),
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='toAddress',
        ),
        migrations.AddField(
            model_name='invitation',
            name='toAddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Examiner.examiner'),
        ),
    ]
