# Generated by Django 4.1.1 on 2022-10-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0032_invitation_fromaddress_remove_invitation_toaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='msg',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
