# Generated by Django 4.1.1 on 2022-10-26 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0033_invitation_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examiner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='examiner',
            name='country',
        ),
    ]
