# Generated by Django 4.1.1 on 2022-10-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0034_remove_examiner_city_remove_examiner_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='ead',
            name='gender',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE')], default=1),
        ),
        migrations.AddField(
            model_name='examiner',
            name='gender',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE')], default=1),
        ),
        migrations.AddField(
            model_name='staff',
            name='gender',
            field=models.IntegerField(choices=[(1, 'MALE'), (2, 'FEMALE')], default=1),
        ),
    ]
