# Generated by Django 4.1.1 on 2022-10-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0035_ead_gender_examiner_gender_staff_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ead',
            name='gender',
            field=models.IntegerField(choices=[(0, 'SELECT GENDER'), (1, 'MALE'), (2, 'FEMALE')], default=0),
        ),
    ]
