# Generated by Django 4.1.1 on 2022-12-15 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0035_alter_examiner_cell_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='D_O_B',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
