# Generated by Django 4.1.1 on 2022-10-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0036_alter_ead_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='sortcode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='gender',
            field=models.IntegerField(choices=[(0, 'SELECT GENDER'), (1, 'MALE'), (2, 'FEMALE')], default=0),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.IntegerField(choices=[(0, 'SELECT GENDER'), (1, 'MALE'), (2, 'FEMALE')], default=0),
        ),
    ]
