# Generated by Django 4.1.1 on 2022-12-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0036_examiner_d_o_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='markingvenue',
            name='dayscount',
            field=models.IntegerField(default=0),
        ),
    ]
