# Generated by Django 4.1.1 on 2022-10-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0037_alter_bankbranch_sortcode_alter_examiner_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
