# Generated by Django 4.1.1 on 2022-10-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0038_alter_examiner_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
