# Generated by Django 4.1.1 on 2022-11-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0040_examiner_created_at_examiner_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='code',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
