# Generated by Django 4.1.1 on 2022-11-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0042_alter_district_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
