# Generated by Django 4.1.1 on 2022-11-03 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0043_customuser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LSK', models.IntegerField()),
                ('COPPERBELT', models.IntegerField()),
                ('MONZE', models.IntegerField()),
                ('KAPIRI', models.IntegerField()),
                ('LIVINGSTONE', models.IntegerField()),
                ('CHOMA', models.IntegerField()),
                ('MWANDI', models.IntegerField()),
                ('LUNTE', models.IntegerField()),
                ('MWENSE', models.IntegerField()),
                ('KASENENGWA', models.IntegerField()),
                ('CHISAMBA', models.IntegerField()),
                ('CHIBOMBO', models.IntegerField()),
                ('CHIBOMBO2', models.IntegerField()),
                ('FromDistrict', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.district')),
            ],
        ),
    ]
