# Generated by Django 4.1.1 on 2022-11-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0044_schedulepay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='schedulepay',
            name='FromDistrict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.district', to_field='code'),
        ),
    ]
