# Generated by Django 4.1.1 on 2022-11-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0045_alter_district_code_alter_schedulepay_fromdistrict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulepay',
            name='FromDistrict',
            field=models.ForeignKey(blank=True, db_column='district_code', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.district', to_field='code'),
        ),
    ]
