# Generated by Django 4.1.1 on 2022-11-03 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0046_alter_schedulepay_fromdistrict'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulepay',
            old_name='LSK',
            new_name='LUSAKA',
        ),
    ]
