# Generated by Django 4.1.1 on 2022-11-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0047_rename_lsk_schedulepay_lusaka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulepay',
            name='CHIBOMBO2',
        ),
    ]
