# Generated by Django 4.1.1 on 2022-11-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0048_remove_schedulepay_chibombo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='examiner',
            name='session',
            field=models.ManyToManyField(to='Examiner.session'),
        ),
    ]
