# Generated by Django 4.1.1 on 2022-11-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0050_remove_examiner_session_delete_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name='examiner',
            name='session',
            field=models.ManyToManyField(to='Examiner.session'),
        ),
    ]
