# Generated by Django 4.1.1 on 2022-11-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0051_session_examiner_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='duration',
        ),
    ]
