# Generated by Django 4.1.1 on 2022-11-09 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0054_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='from_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_station', to='Examiner.station'),
        ),
        migrations.AddField(
            model_name='examiner',
            name='to_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_station', to='Examiner.station'),
        ),
    ]
