# Generated by Django 4.1.1 on 2022-11-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0055_examiner_from_station_examiner_to_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.province'),
        ),
    ]
