# Generated by Django 4.1.1 on 2022-11-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0056_alter_station_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='district',
            new_name='province',
        ),
    ]
