# Generated by Django 4.1.1 on 2022-11-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0057_rename_district_station_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='to_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_district', to='Examiner.district'),
        ),
    ]
