# Generated by Django 4.1.1 on 2022-11-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0059_alter_examiner_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examiner',
            name='from_station',
        ),
        migrations.RemoveField(
            model_name='examiner',
            name='to_district',
        ),
        migrations.AddField(
            model_name='examiner',
            name='to_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_province', to='Examiner.province'),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='Examiner.station'),
        ),
    ]
