# Generated by Django 4.1.1 on 2022-11-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0060_remove_examiner_from_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examiner',
            name='to_station',
        ),
        migrations.AlterField(
            model_name='examiner',
            name='to_province',
            field=models.CharField(blank=True, choices=[('LUSAKA', 'LUSAKA'), ('COPPERBELT', 'COPPERBELT'), ('MONZE', 'MONZE'), ('KAPIRI', 'KAPIRI'), ('LIVINGSTONE', 'LIVINGSTONE'), ('CHOMA', 'CHOMA'), ('MWANDI', 'MWANDI'), ('LUNTE', 'LUNTE'), ('MWENSE', 'MWENSE'), ('KASENENGWA', 'KASENENGWA'), ('CHISAMBA', 'CHISAMBA'), ('CHIBOMBO', 'CHIBOMBO')], max_length=50, null=True),
        ),
    ]
