# Generated by Django 4.1.1 on 2022-11-10 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0061_remove_examiner_to_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.FloatField(default=0.0)),
                ('daily_allowance', models.FloatField(default=0.0)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Examiner.examiner')),
            ],
        ),
    ]
