# Generated by Django 4.1.1 on 2022-11-10 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0063_payment_delete_payments_examiner_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examiner',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='examiner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Examiner.examiner'),
            preserve_default=False,
        ),
    ]
