# Generated by Django 4.1.1 on 2022-11-10 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examiner', '0064_remove_examiner_payment_payment_examiner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulepay',
            name='FromDistrict',
            field=models.ForeignKey(blank=True, db_column='station', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examiner.station', to_field='name'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
